apiVersion: v1
kind: Service

metadata:
  name: java-service
  namespace: omar

spec:
  selector:
    app: java-app

  ports:
    - port: 80
      targetPort: 8090
      nodePort: 30080

  type: NodePort
